"""empty message

Revision ID: 06c2244f9a6e
Revises: 95bb0c65aace
Create Date: 2017-05-24 16:47:23.487287

"""

# revision identifiers, used by Alembic.
revision = '06c2244f9a6e'
down_revision = '95bb0c65aace'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport',
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=45), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('iata_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airport')
    # ### end Alembic commands ###
