"""empty message

Revision ID: 20569f7cd566
Revises: 06c2244f9a6e
Create Date: 2017-05-31 11:38:40.582020

"""

# revision identifiers, used by Alembic.
revision = '20569f7cd566'
down_revision = '06c2244f9a6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in',
    sa.Column('airport_id', sa.String(length=3), nullable=False),
    sa.Column('diag_time', sa.DateTime(), nullable=False),
    sa.Column('uti_rate', sa.Float(), nullable=False),
    sa.Column('queue_avgpeople', sa.Float(), nullable=False),
    sa.Column('queue_waitingtime', sa.Float(), nullable=False),
    sa.Column('sys_avgpeople', sa.Float(), nullable=False),
    sa.Column('sys_waitingtime', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.iata_code'], ),
    sa.PrimaryKeyConstraint('airport_id', 'diag_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_in')
    # ### end Alembic commands ###
