"""empty message

Revision ID: 2cd3c08b9169
Revises: e9aac65532e1
Create Date: 2017-07-24 21:37:16.610273

"""

# revision identifiers, used by Alembic.
revision = '2cd3c08b9169'
down_revision = 'e9aac65532e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_in', sa.Column('waitingarea_space', sa.Float(), nullable=False))
    op.add_column('emigration', sa.Column('waitingarea_space', sa.Float(), nullable=False))
    op.add_column('security_checkpoint', sa.Column('waitingarea_space', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_checkpoint', 'waitingarea_space')
    op.drop_column('emigration', 'waitingarea_space')
    op.drop_column('check_in', 'waitingarea_space')
    # ### end Alembic commands ###
