"""empty message

Revision ID: 53cc251a9bda
Revises: c8bc2b2ac8a5
Create Date: 2017-07-24 21:53:41.753560

"""

# revision identifiers, used by Alembic.
revision = '53cc251a9bda'
down_revision = 'c8bc2b2ac8a5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iata_los', sa.Column('space_overdesign_LB', sa.Float(), nullable=False))
    op.add_column('iata_los', sa.Column('space_suboptimum_UB', sa.Float(), nullable=False))
    op.drop_column('iata_los', 'space_overdesign_UB')
    op.drop_column('iata_los', 'space_suboptimum_LB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iata_los', sa.Column('space_suboptimum_LB', mysql.FLOAT(), nullable=False))
    op.add_column('iata_los', sa.Column('space_overdesign_UB', mysql.FLOAT(), nullable=False))
    op.drop_column('iata_los', 'space_suboptimum_UB')
    op.drop_column('iata_los', 'space_overdesign_LB')
    # ### end Alembic commands ###
