"""empty message

Revision ID: 7642c35572cf
Revises: None
Create Date: 2017-07-07 01:07:50.366697

"""

# revision identifiers, used by Alembic.
revision = '7642c35572cf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport',
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('icao_code', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=45), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('check_in',
    sa.Column('airport_id', sa.String(length=3), nullable=False),
    sa.Column('diag_time', sa.Date(), nullable=False),
    sa.Column('uti_rate', sa.Float(), nullable=False),
    sa.Column('queue_avgpeople', sa.Float(), nullable=False),
    sa.Column('queue_waitingtime', sa.Float(), nullable=False),
    sa.Column('sys_avgpeople', sa.Float(), nullable=False),
    sa.Column('sys_waitingtime', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.iata_code'], ),
    sa.PrimaryKeyConstraint('airport_id', 'diag_time')
    )
    op.create_table('emigration',
    sa.Column('airport_id', sa.String(length=3), nullable=False),
    sa.Column('diag_time', sa.Date(), nullable=False),
    sa.Column('uti_rate', sa.Float(), nullable=False),
    sa.Column('queue_avgpeople', sa.Float(), nullable=False),
    sa.Column('queue_waitingtime', sa.Float(), nullable=False),
    sa.Column('sys_avgpeople', sa.Float(), nullable=False),
    sa.Column('sys_waitingtime', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.iata_code'], ),
    sa.PrimaryKeyConstraint('airport_id', 'diag_time')
    )
    op.create_table('security_checkpoint',
    sa.Column('airport_id', sa.String(length=3), nullable=False),
    sa.Column('diag_time', sa.Date(), nullable=False),
    sa.Column('uti_rate', sa.Float(), nullable=False),
    sa.Column('queue_avgpeople', sa.Float(), nullable=False),
    sa.Column('queue_waitingtime', sa.Float(), nullable=False),
    sa.Column('sys_avgpeople', sa.Float(), nullable=False),
    sa.Column('sys_waitingtime', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.iata_code'], ),
    sa.PrimaryKeyConstraint('airport_id', 'diag_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_checkpoint')
    op.drop_table('emigration')
    op.drop_table('check_in')
    op.drop_table('user')
    op.drop_table('airport')
    # ### end Alembic commands ###
