"""empty message

Revision ID: 87256af178d7
Revises: 20569f7cd566
Create Date: 2017-06-07 11:05:40.837262

"""

# revision identifiers, used by Alembic.
revision = '87256af178d7'
down_revision = '20569f7cd566'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emigration',
    sa.Column('airport_id', sa.String(length=3), nullable=False),
    sa.Column('diag_time', sa.Date(), nullable=False),
    sa.Column('uti_rate', sa.Float(), nullable=False),
    sa.Column('queue_avgpeople', sa.Float(), nullable=False),
    sa.Column('queue_waitingtime', sa.Float(), nullable=False),
    sa.Column('sys_avgpeople', sa.Float(), nullable=False),
    sa.Column('sys_waitingtime', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.iata_code'], ),
    sa.PrimaryKeyConstraint('airport_id', 'diag_time')
    )
    op.create_table('security_checkpoint',
    sa.Column('airport_id', sa.String(length=3), nullable=False),
    sa.Column('diag_time', sa.Date(), nullable=False),
    sa.Column('uti_rate', sa.Float(), nullable=False),
    sa.Column('queue_avgpeople', sa.Float(), nullable=False),
    sa.Column('queue_waitingtime', sa.Float(), nullable=False),
    sa.Column('sys_avgpeople', sa.Float(), nullable=False),
    sa.Column('sys_waitingtime', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.iata_code'], ),
    sa.PrimaryKeyConstraint('airport_id', 'diag_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_checkpoint')
    op.drop_table('emigration')
    # ### end Alembic commands ###
