"""empty message

Revision ID: 8dacbb0d795b
Revises: 9ba31d8ad9a6
Create Date: 2017-07-25 11:52:58.628716

"""

# revision identifiers, used by Alembic.
revision = '8dacbb0d795b'
down_revision = '9ba31d8ad9a6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_in', sa.Column('avgwaitingarea_space', sa.Float(), nullable=False))
    op.drop_column('check_in', 'waitingarea_space')
    op.add_column('emigration', sa.Column('avgwaitingarea_space', sa.Float(), nullable=False))
    op.drop_column('emigration', 'waitingarea_space')
    op.add_column('security_checkpoint', sa.Column('avgwaitingarea_space', sa.Float(), nullable=False))
    op.drop_column('security_checkpoint', 'waitingarea_space')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_checkpoint', sa.Column('waitingarea_space', mysql.FLOAT(), nullable=False))
    op.drop_column('security_checkpoint', 'avgwaitingarea_space')
    op.add_column('emigration', sa.Column('waitingarea_space', mysql.FLOAT(), nullable=False))
    op.drop_column('emigration', 'avgwaitingarea_space')
    op.add_column('check_in', sa.Column('waitingarea_space', mysql.FLOAT(), nullable=False))
    op.drop_column('check_in', 'avgwaitingarea_space')
    # ### end Alembic commands ###
