"""empty message

Revision ID: b1dfa29a9bc6
Revises: 87256af178d7
Create Date: 2017-06-09 09:51:00.395634

"""

# revision identifiers, used by Alembic.
revision = 'b1dfa29a9bc6'
down_revision = '87256af178d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('someprocess',
    sa.Column('airport_id', sa.String(length=3), nullable=False),
    sa.Column('diag_time', sa.Date(), nullable=False),
    sa.Column('uti_rate', sa.Float(), nullable=False),
    sa.Column('queue_avgpeople', sa.Float(), nullable=False),
    sa.Column('queue_waitingtime', sa.Float(), nullable=False),
    sa.Column('sys_avgpeople', sa.Float(), nullable=False),
    sa.Column('sys_waitingtime', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.iata_code'], ),
    sa.PrimaryKeyConstraint('airport_id', 'diag_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('someprocess')
    # ### end Alembic commands ###
