"""empty message

Revision ID: c8bc2b2ac8a5
Revises: 2cd3c08b9169
Create Date: 2017-07-24 21:50:31.777364

"""

# revision identifiers, used by Alembic.
revision = 'c8bc2b2ac8a5'
down_revision = '2cd3c08b9169'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iata_los', sa.Column('space_overdesign_UB', sa.Float(), nullable=False))
    op.add_column('iata_los', sa.Column('space_suboptimum_LB', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iata_los', 'space_suboptimum_LB')
    op.drop_column('iata_los', 'space_overdesign_UB')
    # ### end Alembic commands ###
